<?php
include_once 'Point2d.php';

class point3D extends Point2d
{
    public $z;
    public $XYZ = [];
    public function __construct($x, $y,$z)
    {
        parent::__construct($x, $y);
        $this->z =$z;
    }

    /**
     * @param mixed $y
     */
    public function setY($y)
    {
        $this->y = $y;
    }

    /**
     * @return mixed
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * @param mixed $x
     */
    public function setX($x)
    {
        $this->x = $x;
    }

    /**
     * @return mixed
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * @param mixed $z
     */
    public function setZ($z)
    {
        $this->z = $z;
    }

    /**
     * @return mixed
     */
    public function getZ()
    {
        return $this->z;
    }
    public function setXYZ($XYZ)
    {
        parent::setXY($XYZ); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getXYZ()
    {
        array_push($this->XYZ,$this->x);
        array_push($this->XYZ,$this->y);
        array_push($this->XYZ,$this->z);
        return __toString($this->XYZ);
    }
}
$point3D = new Point3D(1,2,3);
echo $point3D ->XYZ;